---
ENABLE_LINTERS:
  - ANSIBLE_ANSIBLE_LINT
  - YAML_YAMLLINT
# APPLY_FIXES: all
# DISABLE:
#   - BASH
#   - C
#   - CREDENTIALS
#   - JSON
#   - CLOUDFORMATION
#   - CSS
#   - EDITORCONFIG
#   - JAVASCRIPT
#   - COPYPASTE
#   - SPELL
#   - PHP
#   - POWERSHELL
#   - PYTHON
#   - RST
#   - SQL
#   - TERRAFORM
#   - GIT
#   - YAML
# DISABLE_LINTERS:
#   - JSON_PRETTIER
#   - MARKDOWN_MARKDOWN_LINK_CHECK
#   - DOCKERFILE_DOCKERFILELINT
#   - JSON_V8R
PRINT_ALL_FILES: false
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
